/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import java.util.ArrayList;
import logica.Usuario;
import logica.Controlador;
import logica.Proveedor;
import logica.Turista;
/**
 *
 * @author kouta
 */
public class ConsultaDeUsuarios extends javax.swing.JInternalFrame {
    
    Controlador control = Controlador.getInstance();
    /**
     * Creates new form listaDeUsuarios
     */
    public ConsultaDeUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbListaUsuarios = new javax.swing.JComboBox<>();
        lblNickname = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cmbListaUsuarios.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cmbListaUsuariosComponentShown(evt);
            }
        });

        lblNickname.setText("Nickname de usuario");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNickname)
                .addGap(18, 18, 18)
                .addComponent(cmbListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(18, 18, 18)
                .addComponent(btnConsultar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String nickname = cmbListaUsuarios.getSelectedItem().toString();
        Usuario consultado = control.ConsultaDeUsuario(nickname);
        if (consultado instanceof Proveedor){
            ConsultaUsuarioProveedor verConsultaUsuarioProveedor = new ConsultaUsuarioProveedor((Proveedor)consultado);
            getParent().add(verConsultaUsuarioProveedor);        
            verConsultaUsuarioProveedor.show();
        } else  {
            ConsultaUsuarioTurista verConsultaUsuarioTurista = new ConsultaUsuarioTurista((Turista)consultado);
            getParent().add(verConsultaUsuarioTurista);
            verConsultaUsuarioTurista.show();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void cmbListaUsuariosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbListaUsuariosComponentShown
  
    }//GEN-LAST:event_cmbListaUsuariosComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cmbListaUsuarios.removeAllItems();
        ArrayList<String> nicknames = control.listaUsuarios();
        for (int i = 0; i < nicknames.size();i++){
            cmbListaUsuarios.addItem(nicknames.get(i));
        }      
    }//GEN-LAST:event_formComponentShown

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cmbListaUsuarios;
    private javax.swing.JLabel lblNickname;
    // End of variables declaration//GEN-END:variables
}
