/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import logica.Controlador;
import logica.Paquete;
import logica.Actividad;
import java.util.List;
/**
 *
 * @author natil
 */
public class ConsultaPaqueteActividadesTuristicas extends javax.swing.JInternalFrame {
    Controlador control = Controlador.getInstance();
    private List<Paquete> paquetes;
    private Paquete paquete;
    private boolean fload=false;
    private boolean floaded=false;
    /**
     * Creates new form ConsultaPaqueteActividadesTuristicas
     */
    public ConsultaPaqueteActividadesTuristicas() {
        initComponents();
    }
    public ConsultaPaqueteActividadesTuristicas(Paquete paquete) {
        initComponents();
        this.paquete = paquete;
        floaded = !floaded;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPaquetes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtValidez = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbActividades = new javax.swing.JComboBox<>();
        btnVer = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consulta de Paquete de Actividades Turisticas");
        setPreferredSize(new java.awt.Dimension(800, 306));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Seleccione un paquete:");

        cmbPaquetes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lista de paquetes actividad turisticas" }));
        cmbPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbPaquetesMouseClicked(evt);
            }
        });
        cmbPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaquetesActionPerformed(evt);
            }
        });

        jLabel2.setText("Datos del paquete seleccionado:");

        jLabel3.setText("Nombre:");

        txtNombre.setEditable(false);

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Periodo de Validez:");

        jLabel6.setText("Descuento:");

        txtDescripcion.setEditable(false);

        txtValidez.setEditable(false);

        txtDescuento.setEditable(false);

        jLabel7.setText("Ver detalles de Actividad Turistica:");

        cmbActividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lista de actividades turisticas" }));

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cmbActividades, 0, 312, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addComponent(txtValidez)
                                    .addComponent(txtDescripcion)
                                    .addComponent(txtDescuento))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVer)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtValidez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void actualizarDatosDePaquete(boolean flag){
        if(flag){
            if(!floaded)
                paquete = paquetes.get(cmbPaquetes.getSelectedIndex());
            txtNombre.setText(paquete.getNombre());
            txtDescripcion.setText(paquete.getDescripcion());
            txtDescuento.setText(String.valueOf(paquete.getDescuento()));
            txtValidez.setText(String.valueOf(paquete.getValidez()));
            cmbActividades.removeAllItems();
            if(!paquete.getListaActividades().isEmpty()){
                List<Actividad> actividades = paquete.getListaActividades();
                for(int i = 0; i < actividades.size() ;i++){
                    cmbActividades.addItem(actividades.get(i).getNombre());
                }
            }
            fload = true;
            if(floaded)
                floaded = !floaded;
        }
    }
    private void cmbPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaquetesActionPerformed
        // TODO add your handling code here:
        actualizarDatosDePaquete(fload);
    }//GEN-LAST:event_cmbPaquetesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        paquetes = control.consultaPaquetes();
        cmbPaquetes.removeAllItems();
        for(int i = 0; i < paquetes.size();i++){
            cmbPaquetes.addItem(paquetes.get(i).getNombre());
        }
        if(floaded)
            cmbPaquetes.setSelectedItem(paquete.getNombre());
        actualizarDatosDePaquete(true);
    }//GEN-LAST:event_formComponentShown

    private void cmbPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPaquetesMouseClicked
        // TODO add your handling code here:
        //actualizarDatosDePaquete();
    }//GEN-LAST:event_cmbPaquetesMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        Paquete paquete = paquetes.get(cmbPaquetes.getSelectedIndex());
        Actividad actividad = paquete.getListaActividades().get(cmbActividades.getSelectedIndex());
        ConsultaActividadTuristica verConsulta = new ConsultaActividadTuristica(actividad);
        getParent().add(verConsulta);
        verConsulta.show();
    }//GEN-LAST:event_btnVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cmbActividades;
    private javax.swing.JComboBox<String> cmbPaquetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValidez;
    // End of variables declaration//GEN-END:variables
}
