/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica.Actividad;
import logica.Controlador;
import logica.Departamento;
import logica.SalidaTuristica;
import logica.Turista;

/**
 *
 * @author Pc
 */
public class InscripcionASalidaTuristica extends javax.swing.JInternalFrame {
     Controlador control = Controlador.getInstance();
     private ArrayList<Departamento> departamentos = null;
     private ArrayList<Turista> turistas= null;
     private ArrayList<SalidaTuristica> salidas;
     private ArrayList<Actividad> actividades;
     private DefaultTableModel tabla = new DefaultTableModel(){
            //que filas y columnas no sean editables
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            };
        };
     /**
     * Creates new form InscripciónASalidaTurística
     */
    public InscripcionASalidaTuristica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbDepartamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbActividad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrFecha = new javax.swing.JSpinner();
        txtCorreo = new javax.swing.JTextField();
        cmbTurista = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNombreTurista = new javax.swing.JTextField();
        aceptarInscripcionSalida = new javax.swing.JButton();
        cancelarInscripcionSalida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();

        setClosable(true);
        setTitle("Inscripción A Salida Turística");
        setPreferredSize(new java.awt.Dimension(900, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDepartamentoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Departamento");

        cmbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbActividad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbActividadItemStateChanged(evt);
            }
        });
        cmbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActividadActionPerformed(evt);
            }
        });

        jLabel8.setText("Actividades Turisticas");

        jLabel4.setText("Datos:");

        scrFecha.setModel(new javax.swing.SpinnerDateModel());
        scrFecha.setEnabled(false);

        txtCorreo.setEditable(false);

        cmbTurista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTurista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTuristaItemStateChanged(evt);
            }
        });

        jLabel5.setText("Turista");

        txtNombreTurista.setEditable(false);

        aceptarInscripcionSalida.setText("Aceptar");
        aceptarInscripcionSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarInscripcionSalidaActionPerformed(evt);
            }
        });

        cancelarInscripcionSalida.setText("Cancelar");

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSalidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(cmbTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(txtNombreTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scrFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelarInscripcionSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aceptarInscripcionSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTurista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreTurista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptarInscripcionSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarInscripcionSalida)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        cmbDepartamento.removeAllItems();
        departamentos = control.listaDepartamentos();
        for (int i = 0; i < departamentos.size();i++){
            cmbDepartamento.addItem(departamentos.get(i).getNombre());
        }
        cmbTurista.removeAllItems();
        turistas = control.listaTurista();
        for (int i = 0; i < turistas.size();i++){
            cmbTurista.addItem(turistas.get(i).getNickname());
        }
        setModeloTabla();
        if(cmbActividad.getItemCount()>0)
            cargarSalidas();
    }//GEN-LAST:event_formComponentShown

    private void cmbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDepartamentoItemStateChanged
        // TODO add your handling code here:
        if (cmbDepartamento.getItemCount()>0){
            cmbActividad.removeAllItems();
            actividades = departamentos.get(cmbDepartamento.getSelectedIndex()).getListaActTur();
            for (int i = 0; i < actividades.size();i++){
                cmbActividad.addItem(actividades.get(i).getNombre());
            }
        }
    }//GEN-LAST:event_cmbDepartamentoItemStateChanged
    private void cargarSalidas(){
        //carga de los datos desde la BD
        salidas = actividades.get(cmbActividad.getSelectedIndex()).getListaSalidaTuristica();
        tabla.setRowCount(0);
        //recorrer la lista y mostrar cada elemento en la tabla
        if (salidas != null){
            for (SalidaTuristica s : salidas){
                Object[] objeto = {s.getNombre(), s.getCantMax(), s.getfAlta(), s.getfSalida(), s.getLugar()};
                if (objeto !=null)
                tabla.addRow(objeto);   
            }
        }
        
    }
    private void cmbTuristaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTuristaItemStateChanged
        // TODO add your handling code here:
        
        if(cmbTurista.getItemCount()>0){
            txtNombreTurista.setText(turistas.get(cmbTurista.getSelectedIndex()).getNombre());
            txtCorreo.setText(turistas.get(cmbTurista.getSelectedIndex()).getCorreo());
            scrFecha.setValue(turistas.get(cmbTurista.getSelectedIndex()).getfNacimiento());
        }
    }//GEN-LAST:event_cmbTuristaItemStateChanged

    private void cmbActividadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbActividadItemStateChanged
        // TODO add your handling code here:
        if(cmbActividad.getItemCount()>0)
            cargarSalidas();
        
    }//GEN-LAST:event_cmbActividadItemStateChanged

    private void aceptarInscripcionSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarInscripcionSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarInscripcionSalidaActionPerformed

    private void cmbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbActividadActionPerformed
    private void setModeloTabla(){   
        //establecemos los nombres de las columnas
        String titulos[] = {"Nombre", "Capacidad", "Fecha Alta", "Fecha Salida", "Lugar"};
        
        tabla.setColumnIdentifiers(titulos);
        tablaSalidas.setModel(tabla);
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarInscripcionSalida;
    private javax.swing.JButton cancelarInscripcionSalida;
    private javax.swing.JComboBox<String> cmbActividad;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JComboBox<String> cmbTurista;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner scrFecha;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreTurista;
    // End of variables declaration//GEN-END:variables
}
