package presentacion;

//import logica.Fabrica;

import javax.swing.JDesktopPane;

//import logica.IControlador;
//import logica.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author natil
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuAltas = new javax.swing.JMenu();
        Usuario = new javax.swing.JMenu();
        altaUsuarioTurista = new javax.swing.JMenuItem();
        altaUsuarioProveedor = new javax.swing.JMenuItem();
        altaActividadTuristica = new javax.swing.JMenuItem();
        altaSalidaTuristica = new javax.swing.JMenuItem();
        altaInscripcionSalidaTuristica = new javax.swing.JMenuItem();
        altaCrearPaquete = new javax.swing.JMenuItem();
        altaAgregarActividadPaquete = new javax.swing.JMenuItem();
        altaDepartamento = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consUsuario = new javax.swing.JMenuItem();
        consActividadTuristica = new javax.swing.JMenuItem();
        consSalidaTuristica = new javax.swing.JMenuItem();
        consPaquete = new javax.swing.JMenuItem();
        menuModificar = new javax.swing.JMenu();
        modUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" turismo.uy Grupo 4");

        contenedorPrincipal.setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/mano.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE)
        );

        contenedorPrincipal.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout contenedorPrincipalLayout = new javax.swing.GroupLayout(contenedorPrincipal);
        contenedorPrincipal.setLayout(contenedorPrincipalLayout);
        contenedorPrincipalLayout.setHorizontalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        contenedorPrincipalLayout.setVerticalGroup(
            contenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        menuAltas.setText("Altas");

        Usuario.setText("Usuario");

        altaUsuarioTurista.setText("Turista");
        altaUsuarioTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaUsuarioTuristaActionPerformed(evt);
            }
        });
        Usuario.add(altaUsuarioTurista);

        altaUsuarioProveedor.setText("Proveedor");
        altaUsuarioProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaUsuarioProveedorActionPerformed(evt);
            }
        });
        Usuario.add(altaUsuarioProveedor);

        menuAltas.add(Usuario);

        altaActividadTuristica.setText("Actividad Turistica");
        altaActividadTuristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaActividadTuristicaActionPerformed(evt);
            }
        });
        menuAltas.add(altaActividadTuristica);

        altaSalidaTuristica.setText("Salida Turistica");
        altaSalidaTuristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaSalidaTuristicaActionPerformed(evt);
            }
        });
        menuAltas.add(altaSalidaTuristica);

        altaInscripcionSalidaTuristica.setText("Inscripcion Salida Turistica");
        menuAltas.add(altaInscripcionSalidaTuristica);

        altaCrearPaquete.setText("Crear Paquete");
        altaCrearPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCrearPaqueteActionPerformed(evt);
            }
        });
        menuAltas.add(altaCrearPaquete);

        altaAgregarActividadPaquete.setText("Agregar Actividad Paquete");
        altaAgregarActividadPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAgregarActividadPaqueteActionPerformed(evt);
            }
        });
        menuAltas.add(altaAgregarActividadPaquete);

        altaDepartamento.setText("Departamento");
        altaDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaDepartamentoActionPerformed(evt);
            }
        });
        menuAltas.add(altaDepartamento);

        barraMenuPrincipal.add(menuAltas);

        menuConsultas.setText("Consultas");

        consUsuario.setText("Usuario");
        consUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consUsuarioActionPerformed(evt);
            }
        });
        menuConsultas.add(consUsuario);

        consActividadTuristica.setText("Actividad Turistica");
        consActividadTuristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consActividadTuristicaActionPerformed(evt);
            }
        });
        menuConsultas.add(consActividadTuristica);

        consSalidaTuristica.setText("Salida Tursitica");
        consSalidaTuristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consSalidaTuristicaActionPerformed(evt);
            }
        });
        menuConsultas.add(consSalidaTuristica);

        consPaquete.setText("Paquete");
        consPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consPaqueteActionPerformed(evt);
            }
        });
        menuConsultas.add(consPaquete);

        barraMenuPrincipal.add(menuConsultas);

        menuModificar.setText("Modificar");

        modUsuario.setText("Usuario");
        modUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modUsuarioActionPerformed(evt);
            }
        });
        menuModificar.add(modUsuario);

        barraMenuPrincipal.add(menuModificar);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaDepartamentoActionPerformed
        AltaDepartamento verAltaDepartamento = new AltaDepartamento();
        contenedorPrincipal.add(verAltaDepartamento);
        verAltaDepartamento.show();
    }//GEN-LAST:event_altaDepartamentoActionPerformed

    private void altaAgregarActividadPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAgregarActividadPaqueteActionPerformed
        AgregarActividadTuristicaPaquete verAgregarActividadPaquete = new AgregarActividadTuristicaPaquete();
        contenedorPrincipal.add(verAgregarActividadPaquete);
        verAgregarActividadPaquete.show();
    }//GEN-LAST:event_altaAgregarActividadPaqueteActionPerformed

    private void altaCrearPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCrearPaqueteActionPerformed
        CrearPaqueteActividadTuristica verCrearPaquete = new CrearPaqueteActividadTuristica();
        contenedorPrincipal.add(verCrearPaquete);
        verCrearPaquete.show();
    }//GEN-LAST:event_altaCrearPaqueteActionPerformed

    private void altaActividadTuristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaActividadTuristicaActionPerformed
        AltaActividadTuristica verAltaActividadTuristica = new AltaActividadTuristica();
        contenedorPrincipal.add(verAltaActividadTuristica);
        verAltaActividadTuristica.show();
    }//GEN-LAST:event_altaActividadTuristicaActionPerformed

    private void altaUsuarioProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuarioProveedorActionPerformed
        AltaUsuarioProveedor verAltaUsuarioProveedor = new AltaUsuarioProveedor();
        contenedorPrincipal.add(verAltaUsuarioProveedor);
        verAltaUsuarioProveedor.show();
    }//GEN-LAST:event_altaUsuarioProveedorActionPerformed

    private void altaUsuarioTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuarioTuristaActionPerformed
        AltaUsuarioTurista verAltaUsuarioTurista = new AltaUsuarioTurista();
        contenedorPrincipal.add(verAltaUsuarioTurista);
        verAltaUsuarioTurista.show();
    }//GEN-LAST:event_altaUsuarioTuristaActionPerformed

    private void consPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consPaqueteActionPerformed
        ConsultaPaqueteActividadesTuristicas verConsultaPaquete = new ConsultaPaqueteActividadesTuristicas();
        contenedorPrincipal.add(verConsultaPaquete);
        verConsultaPaquete.show();
    }//GEN-LAST:event_consPaqueteActionPerformed

    private void consActividadTuristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consActividadTuristicaActionPerformed
        ConsultaActividadTuristica verConsultaActividadTuristica = new ConsultaActividadTuristica();
        contenedorPrincipal.add(verConsultaActividadTuristica);
        verConsultaActividadTuristica.show();
    }//GEN-LAST:event_consActividadTuristicaActionPerformed

    private void consUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consUsuarioActionPerformed
        // TODO add your handling code here:
        ConsultaDeUsuarios verConsultaUsuarios = new ConsultaDeUsuarios();
        contenedorPrincipal.add(verConsultaUsuarios);
        verConsultaUsuarios.show();
    }//GEN-LAST:event_consUsuarioActionPerformed

    private void consSalidaTuristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consSalidaTuristicaActionPerformed
        // TODO add your handling code here:
        ConsultaDeSalidaTuristica verSalidaConsTuristica = new ConsultaDeSalidaTuristica();
        contenedorPrincipal.add(verSalidaConsTuristica);
        verSalidaConsTuristica.show();
    }//GEN-LAST:event_consSalidaTuristicaActionPerformed

    private void altaSalidaTuristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaSalidaTuristicaActionPerformed
        AltaDeSalidaTuristica verAltaSalidaTuristica = new AltaDeSalidaTuristica();
        contenedorPrincipal.add(verAltaSalidaTuristica);
        verAltaSalidaTuristica.show();
    }//GEN-LAST:event_altaSalidaTuristicaActionPerformed

    private void modUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modUsuarioActionPerformed
        ListaUsuarios verListaUsuarios = new ListaUsuarios();
        contenedorPrincipal.add(verListaUsuarios);
        verListaUsuarios.show();
    }//GEN-LAST:event_modUsuarioActionPerformed

       public JDesktopPane obtenerJDesktopPane() {
      //  System.out.print("funcion obtener");
    return contenedorPrincipal;
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Usuario;
    private javax.swing.JMenuItem altaActividadTuristica;
    private javax.swing.JMenuItem altaAgregarActividadPaquete;
    private javax.swing.JMenuItem altaCrearPaquete;
    private javax.swing.JMenuItem altaDepartamento;
    private javax.swing.JMenuItem altaInscripcionSalidaTuristica;
    private javax.swing.JMenuItem altaSalidaTuristica;
    private javax.swing.JMenuItem altaUsuarioProveedor;
    private javax.swing.JMenuItem altaUsuarioTurista;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JMenuItem consActividadTuristica;
    private javax.swing.JMenuItem consPaquete;
    private javax.swing.JMenuItem consSalidaTuristica;
    private javax.swing.JMenuItem consUsuario;
    private javax.swing.JDesktopPane contenedorPrincipal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuAltas;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuModificar;
    private javax.swing.JMenuItem modUsuario;
    // End of variables declaration//GEN-END:variables
}
